name: 'Publication cdb2hibernatedialect'

on:
  push:
    paths:
      - 'contrib/cdb2hibernatedialect/**'
  release:
    types: [published]

jobs:
  publish:
    name: 'Publish'
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: 'Gradle'
        run: |
          echo 'org.gradle.caching=false' >> gradle.properties
          echo 'org.gradle.configuration-cache=false' >> gradle.properties
        working-directory: ./contrib/cdb2hibernatedialect
      - name: 'Build cdb2hibernatedialect'
        run: |
          ./gradlew build
        working-directory: ./contrib/cdb2hibernatedialect
      - name: 'Publish snapshot to OSSRH'
        if: github.event_name == 'push'
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
        run: |
          ./gradlew \
            publishMavenPublicationToSonatypeRepository \
            closeSonatypeStagingRepository
        working-directory: ./contrib/cdb2hibernatedialect
      - name: 'Publish release to OSSRH'
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
        run: |
          ./gradlew \
            -Prelease \
            publishMavenPublicationToSonatypeRepository \
            closeAndReleaseSonatypeStagingRepository
        working-directory: ./contrib/cdb2hibernatedialect
